#!/usr/bin/env python3
"""Render docker-compose.generated.yml from configs/*.yaml."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CONFIGS_DIR = ROOT / "configs"
COMPOSE_NAME = "docker-compose.generated.yml"
IMAGE = "mihomo-proxy-bench"
ID_RE = re.compile(r"^[a-zA-Z0-9][a-zA-Z0-9_-]*$")
REQUIRED_PLACEHOLDERS = (
    "SUB1_URL",
    "SUB2_URL",
    "SUB3_URL",
    "SUB4_URL",
    "SUB5_URL",
    "SUB6_URL",
    "SUB7_URL",
    "SUB8_URL",
    "MIHOMO_API_SECRET",
)
GIT_URL_DEFAULT = "https://github.com/mamonaronov/mihomo-proxy.git"
GIT_REF_DEFAULT = "main"


def die(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)
    raise SystemExit(1)


def discover_configs() -> list[tuple[str, Path]]:
    if not CONFIGS_DIR.is_dir():
        die(f"configs/ not found at {CONFIGS_DIR}")

    found: list[tuple[str, Path]] = []
    seen: dict[str, Path] = {}
    for path in sorted(CONFIGS_DIR.glob("*.yaml")):
        if path.name.startswith("."):
            continue
        instance_id = path.stem
        if not ID_RE.fullmatch(instance_id):
            die(
                f"invalid config id {instance_id!r} from {path.name}: "
                "use only [a-zA-Z0-9_-], start with alphanumeric"
            )
        if instance_id in seen:
            die(f"duplicate id {instance_id!r}: {seen[instance_id].name} and {path.name}")
        seen[instance_id] = path
        found.append((instance_id, path))

    if not found:
        die("configs/ is empty — put at least one *.yaml (filename without .yaml = instance id)")
    return found


def validate_placeholders(instance_id: str, path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    missing = [name for name in REQUIRED_PLACEHOLDERS if f"${{{name}}}" not in text]
    if missing:
        die(
            f"{path.name} (id {instance_id}) is missing placeholders: "
            + ", ".join(f"${{{name}}}" for name in missing)
            + " — entrypoint envsubst will fail"
        )


def mihomo_service(instance_id: str, with_build: bool) -> str:
    lines = [f"  mihomo-bench-{instance_id}:"]
    if with_build:
        lines.extend(
            [
                "    build:",
                # Quote: unquoted # is a YAML comment and would drop the git ref.
                f'      context: "${{MIHOMO_PROXY_GIT_URL:-{GIT_URL_DEFAULT}}}'
                f'#${{MIHOMO_PROXY_REF:-{GIT_REF_DEFAULT}}}"',
            ]
        )
    lines.extend(
        [
            f"    image: {IMAGE}",
            "    pull_policy: never",
            f"    container_name: mihomo-bench-{instance_id}",
            "    restart: unless-stopped",
            "    env_file: .env",
            "    volumes:",
            f"      - ./data/{instance_id}:/etc/mihomo",
            f"      - ./data/{instance_id}:/root/.config/mihomo",
            f"      - ./configs/{instance_id}.yaml:/template/config.yaml:ro",
            "    networks:",
            "      mihomo-bench:",
            "        aliases:",
            f"          - proxy-{instance_id}",
            "    ulimits:",
            "      nofile:",
            "        soft: 1048576",
            "        hard: 1048576",
        ]
    )
    return "\n".join(lines)


def bot_service(ids: list[str]) -> str:
    depends = "\n".join(f"      - mihomo-bench-{i}" for i in ids)
    return "\n".join(
        [
            "  bench-bot:",
            "    build:",
            "      context: ./bot",
            "    image: mihomo-proxy-bench-bot",
            "    pull_policy: never",
            "    container_name: bench-bot",
            "    restart: unless-stopped",
            "    env_file: .env",
            "    environment:",
            f'      BENCH_INSTANCE_IDS: "{",".join(ids)}"',
            '      TELEGRAM_PROXY_URL: "socks5h://proxy:11808"',
            "      RESULTS_PATH: /app/results/probes.db",
            "      PYTHONUNBUFFERED: \"1\"",
            "    volumes:",
            "      - ./results:/app/results",
            "    networks:",
            "      - mihomo-bench",
            "      - telegram-proxy",
            "    depends_on:",
            depends,
        ]
    )


def render(ids: list[str]) -> str:
    services = [mihomo_service(ids[0], with_build=True)]
    for instance_id in ids[1:]:
        services.append(mihomo_service(instance_id, with_build=False))
    services.append(bot_service(ids))
    body = "\n\n".join(services)
    return (
        "# Generated by generate_compose.py — do not edit.\n"
        "name: mihomo-proxy-bench\n"
        "\n"
        "services:\n"
        f"{body}\n"
        "\n"
        "networks:\n"
        "  mihomo-bench:\n"
        "    name: mihomo-bench\n"
        "  telegram-proxy:\n"
        "    external: true\n"
        "    name: telegram-proxy\n"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--write",
        default=str(ROOT / COMPOSE_NAME),
        help=f"output path (default: {COMPOSE_NAME})",
    )
    parser.add_argument(
        "--print-ids",
        action="store_true",
        help="print instance ids to stdout, one per line",
    )
    args = parser.parse_args()

    configs = discover_configs()
    for instance_id, path in configs:
        validate_placeholders(instance_id, path)

    ids = [instance_id for instance_id, _ in configs]
    text = render(ids)
    out = Path(args.write)
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out} ({len(ids)} mihomo + bench-bot)", file=sys.stderr)
    if args.print_ids:
        sys.stdout.write("\n".join(ids) + "\n")


if __name__ == "__main__":
    main()
